import Testing

@testable import AdventOfCode2025

@Test func day7part1ex1() {
    let input = """
        .......S.......
        ...............
        .......^.......
        ...............
        ......^.^......
        ...............
        .....^.^.^.....
        ...............
        ....^.^...^....
        ...............
        ...^.^...^.^...
        ...............
        ..^...^.....^..
        ...............
        .^.^.^.^.^...^.
        ...............
        """.components(separatedBy: "\n")

    #expect(Day7(input: input).part1() == 21)
}

@Test func day7part1() async throws {
    let day = try await Day7(day: 7)

    #expect(day.part1() == 1333)
}
